services:
  neo4j:
    image: neo4j:5.20.0-community-bullseye
    container_name: neo4j-container
    networks:
      - app-network
    ports:
      - "7474:7474" # Neo4j HTTP port
      - "7687:7687" # Neo4j Bolt port
    # volumes:  #NOTE: persist neo4j storage
    #   - /home/hshazly/workspace/logs/neo4j/data/:/var/lib/neo4j/data
    #   - /home/hshazly/workspace/logs/neo4j/import/:/var/lib/neo4j/import
    #   - /home/hshazly/workspace/logs/neo4j/plugins/:/var/lib/neo4j/plugins

    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc-extended"]'

      NEO4J_AUTH: neo4j/password
      NEO4J_memory_heap_initial/_size: 1G
      NEO4J_memory_heap_max/_size: 1G
      NEO4J_server_memory_pagecache_size: 2G

  job-dispatcher:
    container_name: job-dispatcher-container
    build:
      context: ../.
      dockerfile: docker/spark.Dockerfile
    environment:
      SPARK_MODE: "master"
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
      SPARK_USER: "spark"
    networks:
      - app-network
    ports:
      - "8000:8000" # Job Dispatcher Server
      - "18080:18080" # Spark History Server
      - "4040:4040" # Adjust this port based on your Spark setup
      - "7077:7077" # Spark master
      - "8080:8080" # Spark Master webUI 
    #  volumes:
    #   - /home/hshazly/workspace/logs/job-dispatcher/spark/:/opt/spark/logs/
    #   - /home/hshazly/workspace/logs/job-dispatcher/:/tmp/
    #   # - /home/hshazly/.ssh/:/opt/octopus_key/

  spark-worker:
    container_name: spark-worker
    image: bitnami/spark:3.5.1
    environment:
      SPARK_MODE: "worker"
      SPARK_MASTER_URL: "spark://job-dispatcher-container:7077"
      SPARK_WORKER_MEMORY: "370G"
      SPARK_WORKER_CORES: "48"
      SPARK_RPC_AUTHENTICATION_ENABLED: "no"
      SPARK_RPC_ENCRYPTION_ENABLED: "no"
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: "no"
      SPARK_SSL_ENABLED: "no"
      SPARK_USER: "spark"
    networks:
      - app-network
  #  volumes:
  #   - /home/hshazly/workspace/spark-worker-logs/:/opt/spark/logs/

  # arrow-flight: 
  #   container_name: arrow-flight-server-container
  #   build:
  #      context: .
  #      dockerfile: dockerfiles/flight-server.Dockerfile
  #   networks:
  #     - app-network
  #   ports:
  #     - 8888:8888 # Arrow Flight Server Port
  #   # volumes:
  #   #   - /home/hshazly/workspace/arrow-flight-logs/:/tmp/

networks:
  app-network:
    driver: bridge

#volumes:
#   /home/hshazly/workspace/logs/neo4j/:
# /home/hshazly/workspace/logs/job-dispatcher/:
# /home/hshazly/workspace/logs/spark-worker-logs/:
