version: '3.8'

services:
  spark-neo4j:
    image: shazly/neo4jspark-server:v1
    container_name: spark-neo4j-server
    ports:
      - "8000:8000" # Job Dispatcher Server
      - "18080:18080" # Spark History Server
      - "4040:4040"  # Adjust this port based on your Spark setup
      - "7474:7474"  # Neo4j HTTP port
      - "7687:7687"  # Neo4j Bolt port
    networks:
      - app-network
    volumes: # Good to mount neo4j important dirs (e.g. plugins, data, logs) to host directories
      # - <path-to-octopus-repo-host>:/opt/octopus
      # - <path-to-job-dispatcher-server-logs>:/tmp/
    environment:
      NEO4J_apoc_export_file_enabled: ´true´
      NEO4J_apoc_import_file_enabled: ´true´
      NEO4J_apoc_import_file_use__neo4j__config: ´true´
      NEO4J_PLUGINS: ´["apoc-extended"]´

      NEO4J_AUTH: neo4j/password
      NEO4J_memory_heap_initial/_size: 31G  # Adjust based on server characteristics 
      NEO4J_memory_heap_max/_size: 31G  # Adjust based on server characteristics
      NEO4J_server_memory_pagecache_size: 320G # Adjust based on server characteristics

  arrow-flight:
    image: shazly/arrow-flight-spark:v1
    container_name: arrow-flight-server
    tty: true
    ports:
      - "8888:8888"  # Adjust this port based on your Arrow Flight setup
    networks:
      - app-network
    volumes: # Good to mount flight-server logs directory to host
      # - <path-to-octopus-repo-host>:/opt/octopus
      # - <path-to-flight-logs>:/tmp/flight-logs/
    depends_on:
      - spark-neo4j

networks:
  app-network:
    driver: bridge

