services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    networks:
      - app-network
    ports:
      - "7474:7474"  # Neo4j HTTP port
      - "7687:7687"  # Neo4j Bolt port
    volumes:
      - /home/hshazly/workspace/logs/neo4j/data/:/var/lib/neo4j/data
      - /home/hshazly/workspace/logs/neo4j/import/:/var/lib/neo4j/import
      - /home/hshazly/workspace/logs/neo4j/plugins/:/var/lib/neo4j/plugins

    environment:
      NEO4J_apoc_export_file_enabled: ´true´
      NEO4J_apoc_import_file_enabled: ´true´
      NEO4J_apoc_import_file_use__neo4j__config: ´true´
      NEO4J_PLUGINS: ´["apoc-extended"]´

      NEO4J_AUTH: neo4j/password
      NEO4J_memory_heap_initial/_size: 1G 
      NEO4J_memory_heap_max/_size: 1G  
      NEO4J_server_memory_pagecache_size: 2G 

  job-dispatcher:
     container_name: job-dispatcher-container
     build:
       context: .
       dockerfile: spark-server.Dockerfile
       target: spark-master
     entrypoint: ['./spark-entrypoint.sh', 'master']
     networks:
       - app-network
     ports:
       - "8000:8000" # Job Dispatcher Server
       - "18080:18080" # Spark History Server
       - "4040:4040"  # Adjust this port based on your Spark setup
       - "7077:7077" # Spark master
       - "8081:8081" # Spark master webUI
       - "22:22"
     volumes:
      - /home/hshazly/workspace/logs/job-dispatcher/spark/:/opt/spark/logs/
      - /home/hshazly/workspace/logs/job-dispatcher/:/tmp/

  spark-worker:
     container_name: spark-worker-container
     build:
        dockerfile: spark-server.Dockerfile 
        target: spark-worker
     depends_on: 
       - job-dispatcher
     entrypoint: ['./spark-entrypoint.sh', 'worker']
     networks:
       - app-network
     volumes:
      - /home/hshazly/workspace/spark-worker-logs/:/opt/spark/logs/


  #flight-arrow: 
  #  build file

networks:
   app-network:
     driver: bridge

#volumes:
  #   /home/hshazly/workspace/logs/neo4j/:
  # /home/hshazly/workspace/logs/job-dispatcher/:
  # /home/hshazly/workspace/logs/spark-worker-logs/:
